# Generated by Django 6.0.5 on 2026-05-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Bulan Pembayaran')),
                ('year', models.IntegerField(verbose_name='Tahun')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah (Rp)')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='Bukti Pembayaran')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('lunas', 'Lunas'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
