# Generated by Django 6.0.5 on 2026-05-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prestasi', 'Prestasi'), ('pelanggaran', 'Pelanggaran')], max_length=20)),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('points', models.IntegerField(verbose_name='Poin')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tanggal')),
            ],
        ),
    ]
